#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

for file in $(git diff --cached --name-only | grep -E '\.(js)$')
do
  # fix possible issues
  node_modules/.bin/eslint "$file" --fix
  # Add files to staging
  git add $file
  # run eslint only on staged changes, not any un-staged changes
  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file"
  if [ $? -ne 0 ]; then
    echo "ESLint failed: '$file'"
    exit 1 # exit with failure status
  fi
done

